# Autogenerated wrapper script for Pikchr_jll for x86_64-linux-musl
export libpikchr

JLLWrappers.@generate_wrapper_header("Pikchr")
JLLWrappers.@declare_library_product(libpikchr, "libpikchr.so")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libpikchr,
        "lib/libpikchr.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
